version: '3'

services:
  nginx:
    image: nginx:1.20.1-alpine
    container_name: docker_data_nginx
    volumes:
      - "./:/var/www"
      - "./docker/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "3003:80"
      - "453:443"
    environment:
      - NGINX_HOST=localhost
    restart: "no"
    depends_on:
      - app
      - mysqldb
    networks:
      - app_default
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: php_base
    restart: "no"
    volumes:
      - "./docker/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./:/var/www"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: serverName=Docker
    depends_on:
      - mysqldb
    networks:
      - app_default
  mysqldb:
    image: mysql:8.0
    container_name: php_base_db
    restart: "no"
    environment:
      - MYSQL_DATABASE=device
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
    ports:
      - "3316:3306"
    volumes:
      - "./docker_data/db/mysql:/var/lib/mysql"
    networks:
      - app_default

networks:
  app_default:
    driver: bridge
